<?php
return [
    
'DOCKER_PLATAFORMA_PATH'=>env('DOCKER_PLATAFORMA_PATH' ),
'DOCKER_TILESERVER_PATH'=>env('DOCKER_TILESERVER_PATH' ),
'DOCKER_TILESERVER_STYLE_FILE'=> env('DOCKER_TILESERVER_STYLE_FILE'),
'TILES_SERVER_URL'=>env('TILES_SERVER_URL' ),
];

 